TABOO_GROUPS = {
    "serious_illness": {
        "weight": 1.2,
        "words": {
            "cancer",
            "leukemia",
            "leukaemia",
            "tumor",
            "tumour",
            "terminal",
            "chemo",
            "chemotherapy",
            "aids",
            "hiv",
        },
    },
    "death_violence": {
        "weight": 1.0,
        "words": {
            "death",
            "dead",
            "die",
            "dying",
            "kill",
            "killed",
            "murder",
            "suicide",
            "hang",
            "shot",
            "stab",
        },
    },
    "religion": {
        "weight": 0.9,
        "words": {
            "god",
            "jesus",
            "allah",
            "yahweh",
            "christ",
            "christian",
            "christianity",
            "islam",
            "muslim",
            "judaism",
            "jewish",
            "religion",
            "religious",
            "church",
            "mosque",
            "bible",
            "quran",
            "koran",
            "torah",
        },
    },
    "sex_body": {
        "weight": 0.8,
        "words": {
            "sex",
            "sexual",
            "fuck",
            "fucking",
            "cum",
            "penis",
            "vagina",
            "cock",
            "dick",
            "pussy",
            "tits",
            "boobs",
            "ass",
            "arse",
        },
    },
    "disability_mental": {
        "weight": 0.9,
        "words": {
            "autistic",
            "autism",
            "retard",
            "retarded",
            "disabled",
            "disability",
            "mental",
            "depression",
            "anxiety",
            "adhd",
        },
    },
}

UK_INSULT_PATTERNS = {
    "family_target": {
        "weight": 0.6,
        "patterns": [
            r"\byer (na|mum|mam|ma|da|dad)\b",
            r"\byour (mum|dad)\b",
            r"\bhis (mum|dad)\b",
            r"\bher (mum|dad)\b",
        ],
    },
    "class_marker": {
        "weight": 0.6,
        "patterns": [
            r"\bgot an asbo\b",
            r"\bon the dole\b",
            r"\bbenefits\b",
            r"\bcouncil (estate|house|flat)\b",
            r"\bfree school meals\b",
            r"\bjobcentre\b",
        ],
    },
    "low_status_behaviour": {
        "weight": 0.5,
        "patterns": [
            r"\bsells avon\b",
            r"\bshops at (aldi|lidl|iceland)\b",
            r"\bdrinks (white lightning|frosty jacks)\b",
            r"\bsmokes rollies\b",
            r"\bwears trackies\b",
            r"\bwears sliders\b",
        ],
    },
    "appearance_based": {
        "weight": 0.4,
        "patterns": [
            r"\bginger\b",
            r"\bgreasy\b",
            r"\bmanky\b",
            r"\bsmells\b",
            r"\blooks like\b",
        ],
    },
    "intelligence_insult": {
        "weight": 0.4,
        "patterns": [
            r"\bthick as\b",
            r"\bthick cunt\b",
            r"\bthick\b",
            r"\bstupid\b",
            r"\bdaft\b",
            r"\bnumpty\b",
            r"\bmuppet\b",
        ],
    },
    "behavioural_insult": {
        "weight": 0.4,
        "patterns": [
            r"\bnonce\b",
            r"\bweird cunt\b",
            r"\babsolute (weapon|meltdown|state)\b",
            r"\bembarrassment\b",
        ],
    },
    "deadpan_britishisms": {
        "weight": 0.3,
        "patterns": [
            r"\bit's just\b",
            r"\bfair enough\b",
            r"\bto be fair\b",
            r"\bnot being funny\b",
            r"\bno offence\b",
        ],
    },
}
